/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xando;

import java.awt.Color;
import java.awt.GridLayout;
import java.awt.Image;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author TyCy
 */
public class CoreXandO extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    static int winnerx = 0;
    static int winnero = 0;
    byte value = 0;
    Score s = new Score();
    static int scorex = 0;
    static int scoreo = 0;
    char getResult = ' ';
    
    public CoreXandO() {
        super("X and O game | Created by TyCy");
        initComponents();
        xpane.setText(Integer.toString(Score.scx));
        opane.setText(Integer.toString(Score.sco));
        
         dit.setDisabledIcon(ditt);
         dit.setEnabled(false);
    }
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        xpane = new javax.swing.JTextPane();
        dit = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        opane = new javax.swing.JTextPane();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridLayout(4, 3, 5, 5));

        xpane.setEditable(false);
        xpane.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 70)); // NOI18N
        xpane.setForeground(new java.awt.Color(0, 153, 255));
        xpane.setAutoscrolls(false);
        jScrollPane4.setViewportView(xpane);

        getContentPane().add(jScrollPane4);
        getContentPane().add(dit);

        opane.setEditable(false);
        opane.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 70)); // NOI18N
        opane.setForeground(new java.awt.Color(255, 51, 51));
        jScrollPane6.setViewportView(opane);

        getContentPane().add(jScrollPane6);

        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);

        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);

        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);

        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt4);

        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        getContentPane().add(bt5);

        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        getContentPane().add(bt6);

        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        getContentPane().add(bt7);

        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        getContentPane().add(bt8);

        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        getContentPane().add(bt9);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
        ImageIcon x  = new ImageIcon(this.getClass().getResource("x.png"));
        ImageIcon o  = new ImageIcon(this.getClass().getResource("o.png"));
        ImageIcon ditt  = new ImageIcon(this.getClass().getResource("dit.png"));
        char[][] checkWinArray = new char[3][3];
        
        public char checkWin(char[][] theArray,int coord1,int coord2,char x){
             theArray[coord1][coord2] = x;
             char winChar=' ';
             if(theArray[0][0] == 'x' && theArray[0][1] == 'x' && theArray[0][2] == 'x'){
                 winChar = 'x';
             }else if(theArray[1][0] == 'x' && theArray[1][1] == 'x' && theArray[1][2] == 'x'){
                 winChar = 'x';
             }else if(theArray[2][0] == 'x' && theArray[2][1] == 'x' && theArray[2][2] == 'x'){
                 winChar = 'x';
             }else if(theArray[0][0] == 'x' && theArray[1][0] == 'x' && theArray[2][0] == 'x'){
                 winChar = 'x';
             }else if(theArray[0][1] == 'x' && theArray[1][1] == 'x' && theArray[2][1] == 'x'){
                 winChar = 'x';
             }else if(theArray[0][2] == 'x' && theArray[1][2] == 'x' && theArray[2][2] == 'x'){
                 winChar = 'x';
             }else if(theArray[0][0] == 'x' && theArray[1][1] == 'x' && theArray[2][2] == 'x'){
                 winChar = 'x';
             }else if(theArray[0][2] == 'x' && theArray[1][1] == 'x' && theArray[2][0] == 'x'){
                 winChar = 'x';
             } 
            //O part
            else if (theArray[0][0] == 'o' && theArray[0][1] == 'o' && theArray[0][2] == 'o') {
                winChar = 'o';
            } else if (theArray[1][0] == 'o' && theArray[1][1] == 'o' && theArray[1][2] == 'o') {
                winChar = 'o';
            } else if (theArray[2][0] == 'o' && theArray[2][1] == 'o' && theArray[2][2] == 'o') {
                winChar = 'o';
            } else if (theArray[0][0] == 'o' && theArray[1][0] == 'o' && theArray[2][0] == 'o') {
                winChar = 'o';
            } else if (theArray[0][1] == 'o' && theArray[1][1] == 'o' && theArray[2][1] == 'o') {
                winChar = 'o';
            } else if (theArray[0][2] == 'o' && theArray[1][2] == 'o' && theArray[2][2] == 'o') {
                winChar = 'o';
            } else if (theArray[0][0] == 'o' && theArray[1][1] == 'o' && theArray[2][2] == 'o') {
                winChar = 'o';
            } else if (theArray[0][2] == 'o' && theArray[1][1] == 'o' && theArray[2][0] == 'o') {
                winChar = 'o';
            }
             
             return winChar;
        }
        
        public void setBoxesText(char x){
            if(x == 'x'){
                scorex++;
                xpane.setText(Integer.toString(scorex));
            }else if(x == 'o'){
                scoreo++;
                opane.setText(Integer.toString(scoreo));
            }
        }
        public void resetButtons(){
            bt1.setEnabled(true);
            bt2.setEnabled(true);
            bt3.setEnabled(true);
            bt4.setEnabled(true);
            bt5.setEnabled(true);
            bt6.setEnabled(true);
            bt7.setEnabled(true);
            bt8.setEnabled(true);
            bt9.setEnabled(true);
        }
        
    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed

        value++;
        if(value % 2 == 0) {
          bt1.setDisabledIcon(o); 
          getResult = checkWin(checkWinArray, 0, 0, 'o');
        }else if(value % 2 == 1){
          bt1.setDisabledIcon(x);
          getResult = checkWin(checkWinArray, 0, 0, 'x');
        }
        if (value > 8 || getResult != ' ') {
            s.getTheWinner(getResult);
            setVisible(false);
            s.setVisible(true);
        }else{
            bt1.setEnabled(false);
        }

    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
         
         value++;
        if(value % 2 == 0) {
          bt2.setDisabledIcon(o); 
          getResult = checkWin(checkWinArray, 0, 1, 'o');
        }else if(value % 2 == 1){
          bt2.setDisabledIcon(x);
          getResult = checkWin(checkWinArray, 0, 1, 'x');
        }
        if (value > 8 || getResult != ' ') {
            s.getTheWinner(getResult);
            setVisible(false);
            s.setVisible(true);
        }else{
            bt2.setEnabled(false);
        }
        
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
     
        
         value++;
        if(value % 2 == 0) {
          bt3.setDisabledIcon(o); 
          getResult = checkWin(checkWinArray, 0, 2, 'o');
        }else if(value % 2 == 1){
          bt3.setDisabledIcon(x);
          getResult = checkWin(checkWinArray, 0, 2, 'x');
        }
        if (value > 8 || getResult != ' ') {
            s.getTheWinner(getResult);
            setVisible(false);
            s.setVisible(true);
        }else{
            bt3.setEnabled(false);
        }
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        value++;
        if(value % 2 == 0) {
          bt4.setDisabledIcon(o); 
          getResult = checkWin(checkWinArray, 1, 0, 'o');
        }else if(value % 2 == 1){
          bt4.setDisabledIcon(x);
          getResult = checkWin(checkWinArray, 1, 0, 'x');
        }
        if (value > 8 || getResult != ' ') {
            s.getTheWinner(getResult);
            setVisible(false);
            s.setVisible(true);
        }else{
            bt4.setEnabled(false);
        }
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
         value++;
        if(value % 2 == 0) {
          bt5.setDisabledIcon(o); 
          getResult = checkWin(checkWinArray, 1, 1, 'o');
        }else if(value % 2 == 1){
          bt5.setDisabledIcon(x);
          getResult = checkWin(checkWinArray, 1, 1, 'x');
        }
        if (value > 8 || getResult != ' ') {
            s.getTheWinner(getResult);
            setVisible(false);
            s.setVisible(true);
        }else{
            bt5.setEnabled(false);
        }
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
         value++;
        if(value % 2 == 0) {
          bt6.setDisabledIcon(o); 
          getResult = checkWin(checkWinArray, 1, 2, 'o');
        }else if(value % 2 == 1){
          bt6.setDisabledIcon(x);
          getResult = checkWin(checkWinArray, 1, 2, 'x');
        }
        if (value > 8 || getResult != ' ') {
            s.getTheWinner(getResult);
            setVisible(false);
            s.setVisible(true);
        }else{
            bt6.setEnabled(false);
        }
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        value++;
        if(value % 2 == 0) {
          bt7.setDisabledIcon(o); 
          getResult = checkWin(checkWinArray, 2, 0, 'o');
        }else if(value % 2 == 1){
          bt7.setDisabledIcon(x);
          getResult = checkWin(checkWinArray, 2, 0, 'x');
        }
        if (value > 8 || getResult != ' ') {
            s.getTheWinner(getResult);
            setVisible(false);
            s.setVisible(true);
        }else{
            bt7.setEnabled(false);
        }
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
       value++;
        if(value % 2 == 0) {
          bt8.setDisabledIcon(o); 
          getResult = checkWin(checkWinArray, 2, 1, 'o');
        }else if(value % 2 == 1){
          bt8.setDisabledIcon(x);
          getResult = checkWin(checkWinArray, 2, 1, 'x');
        }
        if (value > 8 || getResult != ' ') {
            s.getTheWinner(getResult);
            setVisible(false);
            s.setVisible(true);
        }else{
            bt8.setEnabled(false);
        }
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        value++;
        if(value % 2 == 0) {
          bt9.setDisabledIcon(o); 
          getResult = checkWin(checkWinArray, 2, 2, 'o');
        }else if(value % 2 == 1){
          bt9.setDisabledIcon(x);
          getResult = checkWin(checkWinArray, 2, 2, 'x');
        }
        if (value > 8 || getResult != ' ') {
            s.getTheWinner(getResult);
            setVisible(false);
            s.setVisible(true);
        }else{
            bt9.setEnabled(false);
        }
       
    }//GEN-LAST:event_bt9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoreXandO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoreXandO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoreXandO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoreXandO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoreXandO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton dit;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTextPane opane;
    private javax.swing.JTextPane xpane;
    // End of variables declaration//GEN-END:variables
}
